[book]
authors = ["Michal Gniadek"]
language = "en"
multilingual = false
title = "Mój Hack!"

# For github pages
[build]
build-dir = "docs/"

[preprocessor.rolltables]
label-separator = ""
separator = "-"